### ISSUE TITLE
Multiple Tabview after clicking "Finish" in RoutineExerciseView

### ISSUE THREAD

**Issue by alex308248** [alex308248/GymBro#15]
The app will create more tabview after clicking `Finish` button in RoutineExerciseView. Everytime we press `Finish`, it will create one more tabview. Looks like following:
![image](https://user-images.githubusercontent.com/44662448/233234089-17b5febd-69fb-47e9-8727-7b5e9cee76d5.png)

**Comment by YLee2121** [comment]
Interesting one 😨😨😨

I will check also later

**Comment by YLee2121** [comment]
Fix issue by PR #16
