### ISSUE TITLE
Core Data Template

### ISSUE THREAD

**Issue by YLee2121** [alex308248/GymBro#6]
Core Data is the database framework for the IOS APP. 
We will need to configure the project with the core data template by adding the Core Data framework to the project!!

Below is the process of adding the Core Data Framework from GPT.
![image](https://user-images.githubusercontent.com/87312700/231349199-933bca23-7a52-463c-927f-5418db1db4af.png)

**Comment by alex308248** [comment]
Adding Core data in an existing swift project will need the following steps:
1. Make sure our app is working correctly without core data. It should have ViewModels, Models and Data Managers in our project and each part should works. Only if we killed the app the data we saved will disappear.
2. Create a Data Model file
3. Design our database and add it in the Data Model file
4. Replace the functions to core data functions

One example of using Core Data in todo list app:
https://apps4world.com/add-core-data-swiftui-tutorial.html

Another method is to use UserDefault to store the data. But the cons of using UserDefault is causing delay when data is too large. Here is an example vedio:
https://www.youtube.com/watch?v=1QOLiELlpGk&list=PLwvDm4VfkdpheGqemblOIA7v3oq0MS30i&index=5
