### ISSUE TITLE
Add .gitattributes

### ISSUE THREAD

**Issue by YLee2121** [alex308248/GymBro#8]
Encounter the error of damaging .pbxproj file while merging the branch. 
Please add the .gitattributes on your own working branch if needed, and follow the reference.

Reference:
https://thoughtbot.com/blog/xcode-and-git-bridging-the-gap

**Comment by alex308248** [comment]
Should I add it in my branch or the version1 branch or add in both of them? I encounter the conflict of xcodeproj QAQ

**Comment by YLee2121** [comment]
@alex308248 
Add on the branch which you would need to work on. 
I don't think adding on the Version 1 is necessary because the working branch will PR into Version 1 at the end.

**Comment by alex308248** [comment]
I added the .gitattributes file in version1. Try the following cmds. 
```
git checkout version1
git pull
git checkout "your branch"
git merge version1
```

**Comment by YLee2121** [comment]
@alex308248 
Are we gonna update the .gitignore for not tracking the project file?

This is the code we discussed.

---
```
# .gitignore for SwiftUI project in Xcode

# Xcode project file
*.pbxproj

# Xcode user-specific settings
*.xcuserdata/

# Xcode workspace shared data
*.xcworkspace/xcshareddata/

# Xcode workspace user-specific settings
*.xcworkspace/xcuserdata/

# Xcode scheme user-specific settings
*.xcuserdatad/
```

And the suggestion from GPT

---

![image](https://user-images.githubusercontent.com/87312700/231876332-848a88c7-6649-49ca-8b34-ae59e01432e6.png)

**Comment by alex308248** [comment]
> Are we gonna update the .gitignore for not tracking the project file?

Nope. It will cause missing pbxproj file and xcode crashing. Adding .gitattribute is a better solution.

**Comment by YLee2121** [comment]
> > Are we gonna update the .gitignore for not tracking the project file?
> 
> Nope. It will cause missing pbxproj file and xcode crashing. Adding .gitattribute is a better solution.

Understand!

**Comment by alex308248** [comment]
Pls let me know if there is any issue 👍

**Comment by YLee2121** [comment]
@alex308248 when you think it's ready, please feel free to close the issue.

**Comment by alex308248** [comment]
Fixed.
